config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :products do
    member do
      get 'checkout'
      get "success" => "products#stripe_success", as: :stripe_success
      get "cancel" => "products#stripe_cancel", as: :stripe_cancel
    end
  end
  get "user_products" => "products#user_products"
  get "my_products" => "products#my_products"
  # resources :checkout, only: [:new, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_handler.rb
class EmailHandler
    def initialize(emails)
        @emails = emails
    end
    
    def get_data
        emails.map { |email| EmailValues.new(email).to_h }
    end
    
    private
    attr_reader :emails
end

app/models/email_values.rb
class EmailValues
    #example for value object design pattern
    def initialize(email)
        @email = email
    end
    
    def name
        email.match(/([^@]*)/).to_s
    end
    
    def domain
        email.split("@").last
    end
    
    def to_h
        { name: name, domain: domain }
    end
    
    private
    attr_reader :email
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_one :payment
    validates :product_name, presence: true, uniqueness: {case_sensitive: false}
    validates :price, presence: true
    after_create :notify_subscribers
    # delegate :amount, to: :payment
    delegate_missing_to :payment

    before_create do
        self.status ||= 'Available'
    end
    enum status: %i[Available Sold Out_of_stock]
    
    def notifyUser(product)
        policy = ProductPolicy.new(product)

        if policy.hasEmail?
            UserMailer.notification_email(product.user).deliver_now
        end
    end

    def product_amount
        payment.amount
    end

    def notify_subscribers
        UserMailer.new_product(self).deliver_now
    end
end

app/models/product_builder.rb
class ProductBuilder
    def initialize
      @product = Product.new
    end
  
    def with_name(name)
      @product.product_name = name
      self
    end
  
    def with_price(price)
      @product.price = price
      self
    end
  
    def with_user(user)
      @product.user = user
      self
    end
  
    def build
      @product.save!
      @product
    end
end

app/models/product_decorator.rb
class ProductDecorator
    def initialize(product)
      @product = product
    end
    
    def name
      @product.product_name
    end
    
    def price(currency)
      case currency
      when :usd
        @product.price / 82.12
      when :eur
        @product.price / 89.39
      end
    end
end

app/models/product_policy.rb
class ProductPolicy
    def initialize(product)
       @product = product
    end

    def hasEmail?
        product.user.email?
    end

    def hasPrice?
        product.price?
    end

    private
    attr_reader :product
end

app/models/product_query.rb
class ProductQuery
    def call
        Product.where(status: "Sold").where('price > ?', 10000)
    end

    def user_products(user)
        user.payments.includes(:product).map {|prod| prod.product if prod.product.status.eql? "Sold" }
    end
end

app/models/singleton_example.rb
# The Singleton design pattern is a creational pattern that restricts the instantiation of a class to a single instance 
# Provides a global point of access to that instance. 
# It ensures that a class has only one instance throughout the lifetime of an application and provides a way to access that instance from anywhere in the codebase.

class SingletonExample
  attr_reader :some_data

  private_class_method :new # Making the constructor private

  @@instance = nil

  def self.instance
    if @@instance.nil?
      @@instance = new
    end
    @@instance
  end

  def initialize
    @some_data = "This is some data"
  end
end

#second way
require 'singleton'

class SingletonExample
  include Singleton

  def message
    "Hello from SingletonExample!"
  end
end

# singleton_instance = SingletonExample.instance
# puts singleton_instance.some_data 
# another_instance = SingletonExample.new
 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :payments
  after_create :welcome_email

  def username
    EmailValues.new(email).name
  end

  def welcome_email
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name,:last_name, :email, :password, :password_confirmation)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name,:last_name, :email, :password, :current_password)}
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  def index
    if params[:query].present?
      @products = Product.where("product_name LIKE ?", "%#{params[:query].capitalize}%")
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.create(product_params)

    if @product.save
      redirect_to root_url
    else
      flash[:error] = "Could not create product"
    end
  end

  def checkout
    @product = Product.find(params[:id])
    StripeChargeService.new(charges_params, current_user, @product, view_context).call
    redirect_to StripeChargeService.new(charges_params, current_user, @product, view_context).call.url
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def user_products
    @products = ProductQuery.new.user_products(current_user)
  end

  def my_products
    
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_url
  end

  def stripe_success
    result = ProductPurchase.call(product_id: params[:id],current_user: current_user)
  
    if result.success?
      redirect_to product_path(result.product), notice: "Purchase Successful"
    else
      redirect_to product_path(params[:id]), alert: result.message
    end
  end

  def stripe_cancel
    @product = Product.find(params[:id])
    redirect_to product_path(@product), notice: "Purchase Unsuccessful, You cancelled"
  end

  private

  def charges_params
    params.permit(:stripe_email, :stripe_token, :id, :price)
  end

  def product_params
    params.require(:product).permit(:product_name, :price, :user_id)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    @form = Forms::UserForm.new(user_form_params)
    
    if @form.save
      sign_in(@form.user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_form_params
    params.permit(:first_name, :last_name,:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Online Reseller</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', products_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to 'New product', new_product_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Purchased products', user_products_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile Options
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to 'My products', my_products_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>

    <ul class="navbar-nav">
    <% presenter = UserPresenter.new(current_user) %> 
     <li class="nav-item">
        <p class="welcome">Welcome <%= presenter.full_name if user_signed_in? %>!
      </li>
    </ul>

    <ul class="navbar-nav">
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= button_to "Sign out", destroy_user_session_path, class: "btn btn-outline-danger sign-out-btn", :method => :delete  %>
        <% end %>
       </li>
    </ul>
  
    <%= form_tag products_path, method: :get, class: "form-inline my-2 my-lg-0" do %>
      <%= text_field_tag :query, "", class: "form-control mr-sm-2", placeholder: "Search for products"  %>
      <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onlinesellingapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
     <% flash.each do |message_type, message| %>
          <div class="alert alert-info"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<div class="container mt-5">
    <%= form_with(model: @product, class: "form-") do |f| %>
        <%= f.label :Name %>
        <%= f.text_field :product_name, class: "form-control", value: @product.product_name %>

        <%= f.label :Price %>
        <%= f.text_field :price, class: "form-control", value: @product.price %>

        <%= f.submit "Update Product", class: "btn btn-primary mt-3" %>
    <% end %>
</div>

app/views/products/index.html.erb
<p class="display-4 ml-5">Products</p>

<div class="container">
  <div class="row">
    <% @products.each do |product| %>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= product.product_name %></h5>
              <p class="card-text"><%= product.price.to_i %></p>
              <p class="card-text"><%= product.status %></p>
              <%= button_to "Show Product",product_path(product.id), class: "btn btn-primary", method: :get %>         
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/products/my_products.html.erb
<h1 class="ml-4"><%= current_user.first_name.capitalize %>'s Products</h1>

<div class="container">
  <div class="row">
    <% current_user.products.each do |product| %>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
                <% product_decorator = ProductDecorator.new(product) %>
                <h3 class="card-title"><%= product_decorator.name %></h3>
                <h5><b>Indian Price</b></h5>
                <h5 class="card-title"><%= product.price %></h5>
                <h5><b>Price in Europe</b></h5>
                <h5 class="card-text"><%= product_decorator.price(:eur).floor %></h5>
                <h5><b>Price in USD</b></h5>
                <h5 class="card-text"><%= product_decorator.price(:usd).floor %></h5>  
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container mt-5">
    <h2>Add a Product</h2>
    <%= form_with(model: @product) do |f| %>
        <%= f.label :Name %>
        <%= f.text_field :product_name, class: "form-control" %>

        <%= f.label :Price %>
        <%= f.text_field :price, class: "form-control" %>

        <%= f.submit "Create Product", class: "mt-3 btn btn-primary" %>
    <% end %>
</div>

app/views/products/show.html.erb
<div class="container">
    <h1>Product <%= @product.product_name %></h1>
    <p>Status : <%= @product.status %> </p>
    <% presenter = UserPresenter.new(current_user) %> 
    <p>by <%= link_to presenter.full_name, my_products_path%></p>
    <p> price <%= @product.price.to_i %></p>
    <br/>
    <% unless current_user.products.include?(@product) %>
        <%= link_to 'Buy Now', checkout_product_path(@product), class: 'btn btn-outline-primary mb-3' if @product.Available? %>
    <% end %>
    <%= link_to "Edit Product", edit_product_path(@product), class: "btn btn-outline-success mb-3" %>
    <%= button_to "Delete Product", product_path(@product),
                                    data:{confirm:"ARE YOU SURE?"}, 
                                    :method => :delete, class: "btn btn-outline-danger sign-out-btn" if current_user.products.include?(@product) %>
        
</div>

app/views/products/user_products.html.erb
<p class="display-4 ml-5"><%= current_user.first_name.capitalize %>'s purchased products</p>

<div class="container">
    <div class="row">
        <% @products.each do |product| %>
            <% if product.present?  %>
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title"><%= product.product_name %></h5>
                            <p class="card-text"><%= product.price.to_i %></p>
                            <p class="card-text"><%= product.status %></p>
                            <%= button_to "Show Product",product_path(product.id), class: "btn btn-primary", method: :get %>         
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>